name: minimal_progress_tracker
description: "An app to track training progress, without ads or in-app purchases"
publish_to: 'none'
version: 1.1.7+32

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  firebase_app_check: ^0.2.2+1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  universal_io: ^2.2.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/icon/icon-adaptive-background.png"
  adaptive_icon_foreground: "assets/icon/icon-adaptive-foreground.png"
  adaptive_icon_monochrome: "assets/icon/icon-adaptive-monochrome.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#95a5a6"
    theme_color: "#34495e"
